import { ConversationMessage } from "./types";

export const FAQ_CONVERSATION_MESSAGES: ConversationMessage[] = [
  {
    id: "q1",
    sender: "client",
    type: "text",
    bubbleSize: "medium",
    content: "What exactly does NavYug specialize in?",
  },
  { id: "t1", type: "typing", thinking: "short" },
  {
    id: "a1",
    sender: "navyug",
    type: "text",
    bubbleSize: "large",
    status: "✓ Responded",
    delayAfter: 700,
    content: "We're a premium digital product studio focused on high-performance Web Platforms, scalable SaaS Development, AI Automation, and strategic Brand Identity. Everything is custom-engineered for measurable business impact.",
  },
  {
    id: "q2",
    sender: "client",
    type: "text",
    bubbleSize: "medium",
    content: "How long does a typical project take?",
  },
  { id: "t2", type: "typing", thinking: "long" },
  {
    id: "a2",
    sender: "navyug",
    type: "text",
    bubbleSize: "large",
    status: "✓ Responded",
    delayAfter: 700,
    content: "Our timelines are transparent. Marketing & brand sites take 3–5 weeks. Complex SaaS applications or AI integrations take 8–12 weeks. We deploy iteratively so you see usable progress from week two.",
  },
  {
    id: "q3",
    sender: "client",
    type: "text",
    bubbleSize: "medium",
    content: "Do you build with low-code tools or custom code?",
  },
  { id: "t3", type: "typing", thinking: "short" },
  {
    id: "a3",
    sender: "navyug",
    type: "text",
    bubbleSize: "large",
    status: "✓ Responded",
    delayAfter: 700,
    content: "Custom code first. We leverage modern frameworks like Next.js, React, and Node.js to accelerate development, but everything we ship is 100% bespoke code with zero vendor lock-in as you scale.",
  },
  {
    id: "q4",
    sender: "client",
    type: "text",
    bubbleSize: "medium",
    content: "What is your pricing structure?",
  },
  { id: "t4", type: "typing", thinking: "medium" },
  {
    id: "a4",
    sender: "navyug",
    type: "text",
    bubbleSize: "medium",
    status: "✓ Responded",
    delayAfter: 700,
    content: "We price based on the value delivered, not hourly estimates. Engagements start at $10k for marketing platforms with transparent, fixed proposals after discovery.",
  },
  {
    id: "cta1",
    sender: "navyug",
    type: "cta",
    content: "That's the overview. Every project is different. Let's talk about yours.",
  },
];
